name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify AWS Configuration
        run: aws s3 ls --debug

      - name: Verify Terraform Version
        run: terraform --version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Output
        run: terraform output -json  # Debugging step to check raw Terraform output

      - name: Capture Terraform Output for 'instance_public_ip'
        run: |
          echo "Terraform output (raw):"
          terraform output -json  # Print raw output for debugging
          echo "Extracting the public IP..."
          INSTANCE_PUBLIC_IP=$(terraform output -json instance_public_ip | jq -r '.value // "default_value"')  # Default if null
          echo "Captured IP: $INSTANCE_PUBLIC_IP"
          echo "instance_public_ip=$INSTANCE_PUBLIC_IP" >> $GITHUB_ENV  # Write to GitHub environment variable


