name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Verify AWS Configuration
        run: aws s3 ls --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Verify Terraform Version
        run: terraform --version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Capture Specific Terraform Output Using jq
        run: |
          INSTANCE_ID=$(terraform output -json instance_id | jq -r .value)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV  # Pass specific output as env var

      - name: Use Terraform Output
        run: |
          echo "Terraform output for instance ID: $INSTANCE_ID"

      - name: Capture Full Terraform Output
        run: |
          terraform output -json > terraform_output.json
          echo "Terraform output saved to terraform_output.json"
      
      - name: Upload Terraform Output as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-output
          path: terraform_output.json

      - name: Terraform Apply
        run: terraform apply -auto-approve
