name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Output
        run: |
          echo "Raw Terraform output (JSON format):"
          terraform output -json

      - name: Extract the Public IP
        run: |
          # Capture the terraform output for 'instance_public_ip'
          echo "Extracting the public IP..."

          # Get the raw output from Terraform for the specific variable
          OUTPUT=$(terraform output -json instance_public_ip)
          echo "Raw output for instance_public_ip: $OUTPUT"

          # Remove any surrounding quotes and assign the value directly
          INSTANCE_PUBLIC_IP=$(echo $OUTPUT | tr -d '"')  # Strip the quotes

          # Debug the captured IP to confirm it's correct
          echo "Captured Public IP: $INSTANCE_PUBLIC_IP"
          
          # Write the value to GitHub Actions environment variable
          echo "instance_public_ip=$INSTANCE_PUBLIC_IP" >> $GITHUB_ENV

      - name: Use Terraform Output
        run: |
          echo "Captured Public IP from Terraform: ${{ env.instance_public_ip }}"
